package algorithm;  
// Declares the package where this class is organized

public class Even_Odd {  
// Defines a public class named Even_Odd

	public static void main(String[] args) {  
	// Main method where Java programs start execution
		
		// TODO Auto-generated method stub
		// This comment was generated by the IDE (Eclipse) as a placeholder
	}

	public void EvenOrOdd(int num) {  
	// A method that checks whether a number is even or odd
	// It accepts an integer parameter named 'num'
		
		if(num % 2 == 0) {  
		// The modulus operator (%) finds the remainder after division by 2
		// If the remainder is 0, the number is even
		
			System.out.println(num + "is an even number");  
			// Print that the number is even
			
			return;  
			// Exit the method immediately after printing
		}
		
		System.out.println(num + "is an odd number");  
		// If the number is not divisible by 2, it is odd
	}

}